# docker-compose.consumer.yml
# This file defines the consumer service setup.

version: '2'

services:
  my-python-consumer:
    build: ../../src
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - 9094:9094
    environment:
      CONSUMER_AUTO_OFFSET_RESET: earliest
      CONSUMER_BOOTSTRAP_SERVER: kafka:9092
      CONSUMER_GROUP_ID: fetch-de-assessment-consumer
      CONSUMER_KAFKA_TOPIC: user-login
      CONSUMER_MESSAGE_LIMIT: 1
      CONSUMER_WAIT_TIME: 1.0
      LOGGER_LEVEL: INFO
      PRODUCER_BOOTSTRAP_SERVER: kafka:9092
      PRODUCER_CLIENT_ID: fetch-de-assessment-processor
      PRODUCER_KAFKA_TOPIC: processed-user-logins
      PRODUCER_WAIT_TIME: 0.01
    networks:
      - kafka-consumer-network