# docker-compose.consumer.yml
# This file defines the consumer service setup.

version: '2'

services:
  my-python-consumer:
    build: ../../src
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - 9094:9094
    environment:
      AUTO_OFFSET_RESET: earliest
      BOOTSTRAP_SERVER: kafka:9092
      CONSUMER_GROUP_ID: fetch-de-assessment-consumer
      CONSUMER_MESSAGE_LIMIT: 1
      CONSUMER_WAIT_TIME: 1.0
      PROCESSED_LOGIN_TOPIC: processed-user-logins
      USER_LOGIN_TOPIC: user-login
    networks:
      - kafka-consumer-network